---
kind: pipeline
type: docker
name: pyoci

platform:
  os: linux
  arch: arm64

globals:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  - &registry_settings
    registry: ${REGISTRY}
    insecure: true
    <<: *docker_creds

steps:
  - name: build-and-push
    image: plugins/docker
    pull: if-not-exists
    settings:
      <<: *registry_settings
      repo: ${REPO}
      context: .
      dockerfile: docker/Dockerfile
      tags: 
        - '${DRONE_COMMIT_SHA}'
        - 'latest'
      purge: false
